name: Generate Snake Game Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write  # <-- ESSENCIAL!

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: lucasvrmoreira
          outputs: |
            dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-snake.gif
          theme: github-light
          layout: wide

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
